## Site settings
##############################################
title: "siimple"
description: "All that you need to create your website with <strong>siimple</strong>."
version: "3.3.0"
author: "Josemi Juanes, Pablo Marin and David Gomez"
url: "https://docs.siimple.xyz"
license: "MIT License"
repository: "https://github.com/siimple/siimple"
links:
    - title: "Home"
      url: "/index.html"
    - title: "Examples"
      url: "/examples/index.html"
    - title: "GitHub"
      url: "https://github.com/siimple/siimple"
      target: "_blank"

## Theme configuration
##############################################
theme_config:
    color: "blue"
    custom_styles: ["/assets/css/main.css"]
    changes_url: "https://github.com/siimple/siimple/issues/new"
    analytics: "UA-70800807-5"
    search:
        entry_url: "/search.html"
        database_url: "/assets/search.json"
    legal_urls:
        cookies: "https://www.siimple.xyz/legal/cookies.html"
        privacy: "https://www.siimple.xyz/legal/privacy.html"
    copyright: "&copy; 2015-present <strong>siimple</strong>"

## Build settings
##############################################
env: "production"
permalink: "none"
theme: "siimple-theme"
exclude: ["LICENSE", "Gemfile", "Gemfile.lock"]

